export const TOOLBAR_CONSTANTS = Object.freeze({
  STYLE_ID: "yt-turbo-toolbar-style",
  TOOLBOX_ROOT_ID: "yt_extension_toolbox_root",
  TOOLBOX_CONTAINER_ID: "toolbox_extension_container",
  SLOT_PLAYER_CONTROLS: "slot:player_controls",
  SLOT_SHORTS_ACTIONS: "slot:shorts_actions",
  SLOT_WATCH_METADATA: "slot:watch_metadata",
  NAVIGATION_FINISH_EVENT: "yt-navigate-finish",
  PAGE_TYPE_CHANGED_EVENT: "yt-page-type-changed",
  PAGE_DATA_UPDATED_EVENT: "yt-page-data-updated",
  SHORTS_TARGET_SELECTOR: "#navigation-button-down",
  WATCH_METADATA_CONTAINER_SELECTOR: "ytd-watch-metadata",
  WATCH_METADATA_TARGET_SELECTOR: "#top-level-buttons-computed, #actions-inner, #actions, #owner",
  WATCH_METADATA_ACTION_HOST_IDS: Object.freeze(new Set<string>(["top-level-buttons-computed", "actions-inner", "owner"])),
  GRID_COLUMNS: 3,
  PANEL_BORDER_RADIUS_PX: 12,
  PANEL_PADDING_PX: 10,
  PANEL_BOTTOM_OFFSET_PX: 60,
  PANEL_BUTTON_SIZE_PX: 38,
  PANEL_BUTTON_RADIUS_PX: 8,
  PANEL_BUTTON_GAP_PX: 6,
  BUTTON_SIZE_PX: 36,
  ICON_SIZE_PX: 20,
  SHORTS_ICON_SIZE: 32,
  SHORTS_ACTION_BUTTON_STYLE: "display:flex;justify-content:center;align-items:center;width:100%;height:100%;margin:0;padding:0;border:0;background:transparent;color:inherit;font:inherit;appearance:none;cursor:pointer;",
  ACTION_ICON_SIZE: 18,
  METADATA_BUTTON_HEIGHT_PX: 36,
  METADATA_BORDER_RADIUS_PX: 18,
  METADATA_ICON_SIZE: 20,
  METADATA_FONT_SIZE_PX: 14,
  METADATA_PADDING_HORIZONTAL_PX: 16,
  METADATA_GAP_PX: 6,
  POPOVER_HOVER_SHOW_DELAY_MS: 150,
  POPOVER_HOVER_HIDE_DELAY_MS: 180,
  POPOVER_SAFETY_MARGIN_PX: 12,
  POPOVER_MENU_ITEM_SELECTOR: 'button[role="menuitem"], button[role="menuitemradio"]',
  POPOVER_MENU_ITEM_TAB_INDEX: -1,
  POPOVER_KEY_ARROW_DOWN: "ArrowDown",
  POPOVER_KEY_ARROW_UP: "ArrowUp",
  POPOVER_KEY_HOME: "Home",
  POPOVER_KEY_END: "End",
  POPOVER_KEY_ESCAPE: "Escape",
  POPOVER_KEY_TAB: "Tab",
  POPOVER_FOCUS_OUTLINE_WIDTH_PX: 2,
  POPOVER_FOCUS_OUTLINE_OFFSET_PX: 2,
  POPOVER_FOCUS_OUTLINE_COLOR: "#ffffff",
  MOUNT_SAFETY_TIMEOUT_MS: 4000,
  DEFAULT_ACTION_ORDER: 100,
  DEFAULT_ACTION_VISIBLE: true,
  DEFAULT_ACTION_ACTIVE: false,
  TOOLTIP_DEFAULT_TEXT: "YouTube Turbo",
  SHORTS_CONTAINER_ID: "script_download_shorts",
  WATCH_METADATA_CONTAINER_ID: "script_outer_box"
});
