export const PAGE_CONSTANTS = {
  TAGS: {
    SECONDARY_WRAPPER: "secondary-wrapper",
    RIGHT_TABS_CONTAINER: "div",
    EXPANDABLE_DESC_BODY_RENDERER: "ytd-expandable-video-description-body-renderer",
    PLACEHOLDER_ANCHOR: "div",
    NOSCRIPT: "noscript"
  },
  IDS: {
    RIGHT_TABS: "right-tabs",
    MATERIAL_TABS: "material-tabs",
    SECONDARY_INNER: "secondary-inner",
    SECONDARY_INNER_TEMP: "secondary-inner-",
    SECONDARY_INNER_WRAPPER: "secondary-inner-wrapper",
    TAB_INFO: "tab-info",
    TAB_COMMENTS: "tab-comments",
    TAB_VIDEOS: "tab-videos",
    TAB_PLAYLIST: "tab-list",
    COMMENT_COUNT_BADGE: "tyt-cm-count",
    TAB_BTN_INFO: "tab-btn1",
    TAB_BTN_COMMENTS: "tab-btn3",
    TAB_BTN_VIDEOS: "tab-btn4",
    TAB_BTN_PLAYLIST: "tab-btn5",
    AYTHL: "aythl"
  },
  SELECTORS: {
    RIGHT_TABS: "#right-tabs",
    MATERIAL_TABS: "#material-tabs",
    TAB_INFO_CONTAINER: "#tab-info",
    TAB_COMMENTS_CONTAINER: "#tab-comments",
    TAB_VIDEOS_CONTAINER: "#tab-videos",
    TAB_PLAYLIST_CONTAINER: "#tab-list",
    TAB_CONTENT_WRAPPER: ".tab-content",
    TAB_CONTENT_CHILDREN: ".tab-content-cld",
    TAB_ACTIVE_CONTENT: ".tab-content-cld:not(.tab-content-hidden)",
    COMMENT_COUNT_BADGE: "#tyt-cm-count",
    YTD_WATCH_FLEXY: "ytd-watch-flexy",
    PRIMARY_INNER: "#primary-inner",
    SECONDARY_INNER: "#secondary-inner",
    SECONDARY_INNER_SCOPED: "#secondary-inner.style-scope.ytd-watch-flexy",
    SECONDARY_INNER_EXACT: "#columns.ytd-watch-flexy > #secondary.ytd-watch-flexy > #secondary-inner, #secondary.ytd-watch-flexy > #secondary-inner, #secondary-inner.style-scope.ytd-watch-flexy",
    SECONDARY_WRAPPER_EXACT: "#secondary-inner.style-scope.ytd-watch-flexy > secondary-wrapper",
    SECONDARY_INNER_WRAPPER: "secondary-wrapper#secondary-inner-wrapper",
    COMMENTS_SECTION: "ytd-comments#comments",
    RELATED_SECTION: "ytd-watch-next-secondary-results-renderer, #columns #secondary #related, #related",
    DESCRIPTION_SECTION: "ytd-watch-metadata #description, #bottom-row #description, #description.ytd-watch-metadata, ytd-expandable-video-description-body-renderer, #below ytd-expandable-video-description-body-renderer, ytd-structured-description-content-renderer",
    WATCH_METADATA: "ytd-watch-metadata",
    EXPANDABLE_DESCRIPTION: "ytd-expandable-video-description-body-renderer",
    TEXT_INLINE_EXPANDER: "ytd-text-inline-expander",
    COMMENTS_HEADER_RENDERER: "ytd-comments-header-renderer",
    LIVE_CHAT_FRAME: "ytd-live-chat-frame#chat",
    PLAYLIST_PANEL: "ytd-playlist-panel-renderer",
    ENGAGEMENT_PANEL: "ytd-engagement-panel-section-list-renderer",
    SIZE_BUTTON: "ytd-watch-flexy #ytd-player button.ytp-size-button",
    TYT_INFO_RENDERER: "ytd-expandable-video-description-body-renderer[tyt-info-renderer]",
    TYT_MAIN_INFO: "[tyt-main-info]",
    TAB_BTN_COMMENTS: "#tab-btn3",
    TAB_BTN_PLAYLIST: "#tab-btn5",
    TAB_BTN_INFO: "#tab-btn1",
    TAB_BTN_VIDEOS: "#tab-btn4",
    ENGAGEMENT_PANELS_CONTAINER: "#panels.ytd-watch-flexy",
    ENGAGEMENT_PANEL_ITEM: "ytd-engagement-panel-section-list-renderer",
    TYT_EGM_PANEL_ACTIVE: "[tyt-egm-panel][target-id][visibility]",
    TYT_COMMENTS_HEADER_RENDERER: "[tyt-comments-area] ytd-comments-header-renderer",
    IO_INTERSECTED_ITEMS: "[io-intersected]",
    COMMENT_ENTRY_EXPANDER: "[tyt-comments-area] #contents ytd-expander#expander",
    RESIZABLE_RENDERERS_INFO: "#tab-info ytd-video-description-infocards-section-renderer, #tab-info yt-chip-cloud-renderer, #tab-info ytd-horizontal-card-list-renderer, #tab-info yt-horizontal-list-renderer",
    AYTHL_SANDBOX: "noscript#aythl",
    TEMPLATE_SANDBOX: "ytd-watch-flexy noscript[ns-template]",
    EXTRA_CONTENT_SOURCES: 'ytd-watch-metadata.ytd-watch-flexy div[slot="extra-content"] > *, ytd-watch-metadata.ytd-watch-flexy #extra-content > *',
    UPLOAD_INFO: "#primary.ytd-watch-flexy ytd-watch-metadata #upload-info",
    MOVIE_PLAYER: "#movie_player",
    HIDDEN_CONTAINER: "[hidden]",
    BROWSE_WITH_SUBTYPE: "ytd-page-manager#page-manager > ytd-browse[page-subtype]",
    DESCRIPTION_PREVIEW_VIEW_MODEL: "yt-description-preview-view-model",
    YTD_APP: "ytd-app"
  },
  CLASSES: {
    SECONDARY_WRAPPER: "tabview-secondary-wrapper",
    TAB_BTN: "tab-btn",
    TAB_BTN_ACTIVE: "active",
    TAB_BTN_HIDDEN: "tab-btn-hidden",
    TAB_CONTENT_CLD: "tab-content-cld",
    TAB_CONTENT_HIDDEN: "tab-content-hidden",
    FONT_SIZE_RIGHT: "font-size-right",
    FONT_SIZE_BTN: "font-size-btn",
    FONT_SIZE_PLUS: "font-size-plus",
    FONT_SIZE_MINUS: "font-size-minus",
    PLACEHOLDER_ANCHOR: "tyt-relocator-anchor",
    METADATA_HOVER: "tyt-metadata-hover",
    METADATA_HOVER_RESIZED: "tyt-metadata-hover-resized"
  },
  ATTRIBUTES: {
    TYT_DI: "tyt-di",
    TYT_TAB: "tyt-tab",
    TYT_TAB_CONTENT: "tyt-tab-content",
    TYT_HIDDEN: "tyt-hidden",
    TYT_INFO_RENDERER: "tyt-info-renderer",
    TYT_MAIN_INFO: "tyt-main-info",
    TYT_INFO_RENDERER_FRONT: "tyt-info-renderer-front",
    TYT_INFO_RENDERER_BACK: "tyt-info-renderer-back",
    NS_TEMPLATE: "ns-template",
    TYT_DATA_OBSERVED: "tyt-data-observed",
    TYT_DATA_CHANGE_COUNTER: "tyt-data-change-counter",
    TYT_CLONE_REFRESH_COUNT: "tyt-clone-refresh-count",
    HIDE_DEFAULT_TEXT_INLINE_EXPANDER: "hide-default-text-inline-expander",
    USERSCRIPT_SCROLLBAR: "userscript-scrollbar-render",
    THEATER: "theater",
    COLLAPSED: "collapsed",
    TABVIEW_LOADED: "tabview-loaded",
    TYT_CHAT: "tyt-chat",
    TYT_CHAT_COLLAPSED: "tyt-chat-collapsed",
    TYT_ACTIVE_CHAT_FRAME: "tyt-active-chat-frame",
    TYT_CHAT_CONTAINER: "tyt-chat-container",
    TYT_PLAYLIST_EXPANDED: "tyt-playlist-expanded",
    TYT_EGM_PANEL: "tyt-egm-panel",
    TYT_EGM_PANEL_WRAP: "tyt-egm-panel_",
    TYT_EGM_PANEL_JCLMD: "tyt-egm-panel-jclmd",
    TYT_VISIBLE_AT: "tyt-visible-at",
    TYT_COMMENTS_AREA: "tyt-comments-area",
    TYT_COMMENTS_VIDEO_ID: "tyt-comments-video-id",
    TYT_COMMENTS_DATA_STATUS: "tyt-comments-data-status",
    TYT_COMMENT_DISABLED: "tyt-comment-disabled",
    TYT_COMMENTS_HEADER_FIELD: "tyt-comments-header-field",
    FIELD_OF_CM_COUNT: "field-of-cm-count",
    TYT_CONTENT_COMMENT_ENTRY: "tyt-content-comment-entry",
    TYT_VIDEOS_LIST: "tyt-videos-list",
    KEEP_COMMENTS_SCROLLER: "keep-comments-scroller",
    IO_INTERSECTED: "io-intersected",
    FULL_BLEED_NO_MAX_WIDTH_COLUMNS: "full-bleed-no-max-width-columns",
    ENGAGEMENT_PANEL_VISIBILITY_EXPANDED: "ENGAGEMENT_PANEL_VISIBILITY_EXPANDED",
    ENGAGEMENT_PANEL_VISIBILITY_HIDDEN: "ENGAGEMENT_PANEL_VISIBILITY_HIDDEN"
  },
  VALUES: {
    TABVIEW_LOADED_ICP: "icp"
  },
  ANIMATIONS: {
    RELATED_ELEMENT_PROVIDED: "relatedElementProvided"
  },
  PATTERNS: {
    CHANNEL_ID_ABOUT: /\/channel\/UC[-_a-zA-Z0-9+=.]{22}\/about/,
    CHANNEL_HANDLE_ABOUT: /\/@[a-zA-Z0-9_.-]+\/about/,
    CHANNEL_CUSTOM_ABOUT: /\/(?:c|user)\/[a-zA-Z0-9_.-]+\/about/
  },
  MASKS: {
    TOKEN_MASK: 0x3fffffff
  },
  THRESHOLDS: {
    MINIPLAYER_MIN_TIME_SEC: 3,
    PLAYLIST_PROTECT_MAX_ACCESS: 3
  },
  TIMEOUTS: {
    ELEMENT_WAIT_MS: 5000,
    CHAT_FRAME_READY_MS: 700,
    HOVER_RESIZE_DEADLINE_MS: 300,
    ABOUT_POPUP_TRIGGER_MS: 80,
    LINKED_COMMENT_READY_MS: 8000
  },
  HOVER: {
    OVERFLOW_TOLERANCE_PX: 4
  },
  FONT_SIZE: {
    MIN_PX: 10,
    MAX_PX: 28,
    STEP_PX: 1,
    DEFAULT_PX: 14
  },
  SVG: {
    COMMENTS: `<path d="M80 27H12A12 12 90 0 0 0 39v42a12 12 90 0 0 12 12h12v20a2 2 90 0 0 3.4 2L47 93h33a12 12 90 0 0 12-12V39a12 12 90 0 0-12-12zM20 47h26a2 2 90 1 1 0 4H20a2 2 90 1 1 0-4zm52 28H20a2 2 90 1 1 0-4h52a2 2 90 1 1 0 4zm0-12H20a2 2 90 1 1 0-4h52a2 2 90 1 1 0 4zm36-58H40a12 12 90 0 0-12 12v6h52c9 0 16 7 16 16v42h0v4l7 7a2 2 90 0 0 3-1V71h2a12 12 90 0 0 12-12V17a12 12 90 0 0-12-12z"/>`,
    VIDEOS: `<path d="M89 10c0-4-3-7-7-7H7c-4 0-7 3-7 7v70c0 4 3 7 7 7h75c4 0 7-3 7-7V10zm-62 2h13v10H27V12zm-9 66H9V68h9v10zm0-56H9V12h9v10zm22 56H27V68h13v10zm-3-25V36c0-2 2-3 4-2l12 8c2 1 2 4 0 5l-12 8c-2 1-4 0-4-2zm25 25H49V68h13v10zm0-56H49V12h13v10zm18 56h-9V68h9v10zm0-56h-9V12h9v10z"/>`,
    INFO: `<path d="M30 0C13.3 0 0 13.3 0 30s13.3 30 30 30 30-13.3 30-30S46.7 0 30 0zm6.2 46.6c-1.5.5-2.6 1-3.6 1.3a10.9 10.9 0 0 1-3.3.5c-1.7 0-3.3-.5-4.3-1.4a4.68 4.68 0 0 1-1.6-3.6c0-.4.2-1 .2-1.5a20.9 20.9 90 0 1 .3-2l2-6.8c.1-.7.3-1.3.4-1.9a8.2 8.2 90 0 0 .3-1.6c0-.8-.3-1.4-.7-1.8s-1-.5-2-.5a4.53 4.53 0 0 0-1.6.3c-.5.2-1 .2-1.3.4l.6-2.1c1.2-.5 2.4-1 3.5-1.3s2.3-.6 3.3-.6c1.9 0 3.3.6 4.3 1.3s1.5 2.1 1.5 3.5c0 .3 0 .9-.1 1.6a10.4 10.4 90 0 1-.4 2.2l-1.9 6.7c-.2.5-.2 1.1-.4 1.8s-.2 1.3-.2 1.6c0 .9.2 1.6.6 1.9s1.1.5 2.1.5a6.1 6.1 90 0 0 1.5-.3 9 9 90 0 0 1.4-.4l-.6 2.2zm-3.8-35.2a1 1 0 010 8.6 1 1 0 010-8.6z"/>`,
    PLAYLIST: `<path d="M0 3h12v2H0zm0 4h12v2H0zm0 4h8v2H0zm16 0V7h-2v4h-4v2h4v4h2v-4h4v-2z"/>`
  },
  DOM_EVENTS: {
    YT_NAVIGATE_FINISH: "yt-navigate-finish",
    YT_NAVIGATE_START: "yt-navigate-start",
    YT_PAGE_TYPE_CHANGED: "yt-page-type-changed",
    YT_ACTION: "yt-action",
    ANIMATION_START: "animationstart"
  }
} as const;
