export const SUBTITLE_CONSTANTS = {
  STORAGE_KEY_OFFSET: "yt/subtitleOffset",
  DEFAULT_OFFSET_MS: 0,
  STEP_OFFSET_MS: 250,
  MIN_OFFSET_MS: -10000,
  MAX_OFFSET_MS: 10000,
  TIMEDTEXT_API_PATH: "/api/timedtext",
  FALLBACK_CUE_DURATION_MS: 2000,
  MAX_CUE_WINDOW_LOOKBACK_MS: 15000,
  SHORTCUT_ADVANCE_KEY: "[",
  SHORTCUT_DELAY_KEY: "]",
  SHORTCUT_RESET_KEY: "\\"
} as const;
